load("/home/zeus/scRNAseq.rdata")
print("Class of sc1:")
print(class(sc1))
print("Dimensions of sc1:")
print(dim(sc1))
print("Length of sc1:")
print(length(sc1))
print("Summary of sc1:")
print(str(sc1))
